// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElegantnailsstudioSystemManagement.Migrations
{

    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Activo",
                            Nombre = "Uñas"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Activo",
                            Nombre = "Pestañas"
                        });
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("servicio_id");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turno");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicioId");

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Cupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CupoActual")
                        .HasColumnType("integer")
                        .HasColumnName("cupo_actual");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("integer")
                        .HasColumnName("cupo_maximo");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turno");

                    b.HasKey("Id");

                    b.ToTable("cupos", (string)null);
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permisos");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador",
                            Permisos = "gestionar_servicios,gestionar_categorias,gestionar_citas,gestionar_cupos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Cliente",
                            Permisos = "agendar_cita,cancelar_cita,ver_servicios"
                        });
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<int>("Duracion")
                        .HasColumnType("integer")
                        .HasColumnName("duracion");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("Imagen")
                        .HasColumnType("text")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("servicios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Duracion = 30,
                            Estado = true,
                            Nombre = "Manicure Básico",
                            Precio = 8.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Duracion = 45,
                            Estado = true,
                            Nombre = "Pedicure Spa",
                            Precio = 12.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Duracion = 90,
                            Estado = true,
                            Nombre = "Extensiones de Pestañas",
                            Precio = 25.00m
                        });
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@elegantnails.com",
                            Estado = true,
                            FechaRegistro = new DateTime(2025, 11, 13, 22, 53, 31, 395, DateTimeKind.Utc).AddTicks(3277),
                            Nombre = "Administrador",
                            Password = "$2a$11$XysbeHpSlbB7dpckrw9MguXDpPHKO.o1w3joM1U22ym.P5lSrtPpC",
                            RolId = 1,
                            Telefono = "76872677"
                        });
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Cita", b =>
                {
                    b.HasOne("ElegantNailsStudioSystemManagement.Models.Usuario", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElegantNailsStudioSystemManagement.Models.Servicio", "Servicio")
                        .WithMany("Citas")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Servicio", b =>
                {
                    b.HasOne("ElegantNailsStudioSystemManagement.Models.Categoria", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Usuario", b =>
                {
                    b.HasOne("ElegantNailsStudioSystemManagement.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Categoria", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Servicio", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("ElegantNailsStudioSystemManagement.Models.Usuario", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
